# Generated by Django 5.2.4 on 2025-08-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil AWS',
                'verbose_name_plural': 'Perfiles AWS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, unique=True)),
                ('instance_class', models.CharField(max_length=100)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL'), ('mariadb', 'MariaDB'), ('oracle-ee', 'Oracle Enterprise Edition'), ('oracle-se', 'Oracle Standard Edition'), ('oracle-se1', 'Oracle Standard Edition One'), ('oracle-se2', 'Oracle Standard Edition Two'), ('sqlserver-ee', 'SQL Server Enterprise Edition'), ('sqlserver-se', 'SQL Server Standard Edition'), ('sqlserver-ex', 'SQL Server Express Edition'), ('sqlserver-web', 'SQL Server Web Edition'), ('aurora', 'Aurora MySQL'), ('aurora-postgresql', 'Aurora PostgreSQL')], max_length=50)),
                ('engine_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('creating', 'Creando'), ('deleting', 'Eliminando'), ('failed', 'Fallido'), ('inaccessible-encryption-credentials', 'Credenciales de encriptación inaccesibles'), ('incompatible-parameters', 'Parámetros incompatibles'), ('incompatible-restore', 'Restauración incompatible'), ('incompatible-network', 'Red incompatible'), ('incompatible-option-group', 'Grupo de opciones incompatible'), ('incompatible-parameters', 'Parámetros incompatibles'), ('maintenance', 'Mantenimiento'), ('modifying', 'Modificando'), ('rebooting', 'Reiniciando'), ('renaming', 'Renombrando'), ('resetting-master-credentials', 'Reiniciando credenciales maestras'), ('restore-error', 'Error de restauración'), ('storage-full', 'Almacenamiento lleno'), ('storage-optimization', 'Optimización de almacenamiento'), ('upgrading', 'Actualizando')], max_length=100)),
                ('endpoint_address', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint_port', models.IntegerField(blank=True, null=True)),
                ('allocated_storage', models.IntegerField(help_text='Almacenamiento en GB')),
                ('storage_type', models.CharField(choices=[('gp2', 'General Purpose SSD (gp2)'), ('gp3', 'General Purpose SSD (gp3)'), ('io1', 'Provisioned IOPS SSD (io1)'), ('io2', 'Provisioned IOPS SSD (io2)'), ('standard', 'Magnetic')], max_length=20)),
                ('availability_zone', models.CharField(max_length=100)),
                ('multi_az', models.BooleanField(default=False)),
                ('publicly_accessible', models.BooleanField(default=False)),
                ('database_name', models.CharField(blank=True, max_length=100, null=True)),
                ('master_username', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_retention_period', models.IntegerField(help_text='Período de retención en días')),
                ('vpc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subnet_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds_instances', to='core.awsprofile')),
            ],
            options={
                'verbose_name': 'Instancia RDS',
                'verbose_name_plural': 'Instancias RDS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RDSMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('CPUUtilization', 'Utilización de CPU'), ('FreeableMemory', 'Memoria Libre'), ('FreeStorageSpace', 'Espacio Libre de Almacenamiento'), ('DatabaseConnections', 'Conexiones de Base de Datos'), ('ReadIOPS', 'Operaciones de Lectura por Segundo'), ('WriteIOPS', 'Operaciones de Escritura por Segundo'), ('ReadLatency', 'Latencia de Lectura'), ('WriteLatency', 'Latencia de Escritura'), ('NetworkReceiveThroughput', 'Rendimiento de Recepción de Red'), ('NetworkTransmitThroughput', 'Rendimiento de Transmisión de Red')], max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('average', models.FloatField()),
                ('maximum', models.FloatField()),
                ('minimum', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('rds_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.rdsinstance')),
            ],
            options={
                'verbose_name': 'Métrica RDS',
                'verbose_name_plural': 'Métricas RDS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('partial', 'Parcial')], max_length=20)),
                ('instances_found', models.IntegerField(default=0)),
                ('instances_updated', models.IntegerField(default=0)),
                ('instances_created', models.IntegerField(default=0)),
                ('instances_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.awsprofile')),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VpcSecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_group_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('rds_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_groups', to='core.rdsinstance')),
            ],
            options={
                'verbose_name': 'Grupo de Seguridad VPC',
                'verbose_name_plural': 'Grupos de Seguridad VPC',
            },
        ),
        migrations.AddIndex(
            model_name='rdsinstance',
            index=models.Index(fields=['instance_id'], name='core_rdsins_instanc_1eabed_idx'),
        ),
        migrations.AddIndex(
            model_name='rdsinstance',
            index=models.Index(fields=['profile', 'status'], name='core_rdsins_profile_afc071_idx'),
        ),
        migrations.AddIndex(
            model_name='rdsinstance',
            index=models.Index(fields=['engine'], name='core_rdsins_engine_70722a_idx'),
        ),
        migrations.AddIndex(
            model_name='rdsinstance',
            index=models.Index(fields=['last_sync'], name='core_rdsins_last_sy_56746d_idx'),
        ),
        migrations.AddIndex(
            model_name='rdsmetric',
            index=models.Index(fields=['rds_instance', 'metric_name', 'timestamp'], name='core_rdsmet_rds_ins_8267b3_idx'),
        ),
        migrations.AddIndex(
            model_name='rdsmetric',
            index=models.Index(fields=['timestamp'], name='core_rdsmet_timesta_54c9e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rdsmetric',
            unique_together={('rds_instance', 'metric_name', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='vpcsecuritygroup',
            unique_together={('rds_instance', 'security_group_id')},
        ),
    ]
